SportsStore.WebUI/Controllers/CartController.cs
using SportsStore.Core.Interfaces.Managers;
using SportsStore.Core.Models;
using SportsStore.WebUI.Models.Cart;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
	public class CartController : Controller
	{
		private IProductManager _productManager;
		private IOrderManager _orderManager;

		public CartController(IProductManager productManager, IOrderManager orderManager)
		{
			_productManager = productManager;
			_orderManager = orderManager;
		}

		public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
		{
			var product = _productManager.GetAllProducts().FirstOrDefault(x => x.ProductId == productId);
			if (product != null)
			{
				cart.AddItem(product, 1);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
		{
			var product = _productManager.GetAllProducts().FirstOrDefault(x => x.ProductId == productId);
			if (product != null)
			{
				cart.RemoveLine(product);
			}
			return RedirectToAction("Index", new { returnUrl });
		}

		public ViewResult Index(Cart cart, string returnUrl)
		{
			var model = new CartIndexViewModel()
			{
				Cart = cart,
				ReturnUrl = returnUrl
			};
			return View(model);
		}
		public PartialViewResult Summary(Cart cart)
		{
			return PartialView(cart);
		}
		[HttpGet]
		public ViewResult Checkout()
		{
			return View(new ShippingDetails());
		}
		[HttpPost]
		public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
		{
			if (!cart.Lines.Any())
			{
				ModelState.AddModelError("", "Sorry, your cart is empty!");
			}
			if (ModelState.IsValid)
			{
				_orderManager.ProcessOrder(cart, shippingDetails);
				cart.Clear();
				return View("Completed");
			}
			else
			{
				return View(shippingDetails);
			}
		}
	}
}

SportsStore.WebUI/Controllers/NavController.cs
using SportsStore.Core.Interfaces.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class NavController : Controller
    {
		private readonly IProductManager _productManager;
		public NavController(IProductManager productManager)
		{
			_productManager = productManager;
		}
		
		public PartialViewResult Menu(string category = null)
        {
			ViewBag.SelectedCategory = category ;
			var categories = _productManager.GetAllProducts()
				.Select(x => x.Category)
				.Distinct()
				.OrderBy(x => x);
			return PartialView ("FlexMenu", categories);
        }
    }
}

SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Core.Interfaces.Managers;
using SportsStore.WebUI.Models.ProductListModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductManager _productManager;
		private int _pageSize = 4;
		public ProductController(IProductManager productManager)
        {
            _productManager = productManager;
        }
        // GET: Product
        public ViewResult List(string category, int page = 1)
        {
            var productListModel = new ProductListModel()
            {
				Products = _productManager.GetAllProducts()
				.Where(x=> category == null || x.Category == category)
				.OrderBy(x => x.ProductId).Skip((page - 1) * _pageSize).Take(_pageSize).ToArray(),

			PagingInfoModel = new PagingInfoModel()
			{
				TotalItems = category == null ? _productManager.GetAllProducts().Count() : _productManager.GetAllProducts().Where(x => x.Category == category).Count(),
				CurrentPage = page,
				ItemsPerPage = _pageSize
			},
				CurrentCategory = category
			};
			return View("List", productListModel);
        }
		public FileContentResult GetImage(int productId)
		{
			var product = _productManager.GetProductById(productId);
			if (product != null)
			{
				var foto = File(product.ImageData, product.ImageMimeType);
				return File(product.ImageData, product.ImageMimeType);
			}
			return null;
		}
	}
}

SportsStore.WebUI/Views/Shared/ProductSummary.Mobile.cshtml
@model SportsStore.Core.Models.Product
<div data-role="collapsible" data-collapsed="false" data-content-theme="c">
	<h2>@Model.Name</h2>
	<div class="ui-grid-b">
		<div class="ui-block-b">
			@Model.Description
		</div>
		<div class="ui-block-b">
			<strong>(@Model.Price.ToString("c"))</strong>
		</div>
		<div class="ui-block-c">
			@using (Html.BeginForm("AddToCart", "Cart"))
			{
				@Html.HiddenFor(x => x.ProductId);
				@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
				<input type="submit" data-inline="true" data-mini="true" value="Add to cart" />
			}
		</div>
	</div>
</div>

SportsStore.WebUI/Views/Shared/ProductSummary.cshtml
@model SportsStore.Core.Models.Product
<div class="well">
	@if (Model.ImageData != null)
	{
		<div class="pull-left" style="margin-right: 10px">
			<img class="img-thumbnail" width="75" height="75" src="@Url.Action("GetImage","Product",new {productId = Model.ProductId})" />
		</div>
	}
	<h3>
		<strong>@Model.Name</strong>
		<span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
	</h3>
	@using (Html.BeginForm("AddToCart", "Cart"))
	{
		<div class=" pull-right">
			@Html.HiddenFor(x => x.ProductId)
			@Html.Hidden("returnUrl", Request.Url.PathAndQuery)
			<input type="submit" class="btn btn-success" value="Add to cart" />
		</div>
	}
	<span class="lead">@Model.Description</span>
</div>

SportsStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
	<link href="~/Content/ErrorsStyles.css" rel="stylesheet" />
	<script src="~/Scripts/jquery-3.0.0.js"></script>
	<script src="~/Scripts/jquery.validate.js"></script>
	<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
	<title></title>
</head>
<body>
	<div>
		@if (TempData["message"] != null)
		{
			<div class="alert alert-success">@TempData["message"]</div>
		}
		@RenderBody()
	</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.Mobile.cshtml
<!DOCTYPE html>

<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="stylesheet"
		  href="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.css" />
	<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
	<script src="http://code.jquery.com/mobile/1.3.2/jquery.mobile-1.3.2.min.js"></script>
	<title>@ViewBag.Title</title>
</head>
<body>
	<div data-role="page" id="page1">
		<div data-thme="a" data-role="header" data-position="fixed">
			<h3>SportsStore</h3>
			@Html.Action("Menu", "Nav")
		</div>
		<div data-role="content">
			<ul data-role="listview" data-divider-theme="b" data-insert="false">
				@RenderBody()
			</ul>
		</div>
	</div>
</body>
</html>

SportsStore.WebUI/Views/Shared/_Layout.cshtml
@using System.Web.Optimization
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="~/Content/bootstrap.css" rel="stylesheet" />
	<link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
	<link href="~/Content/ErrorsStyles.css" rel="stylesheet" />
	<style>
		.navbar-right {
			float: right !important;
			margin-right: 15px;
			margin-left: 15px;
		}
	</style>
</head>
<body>
	<div class="navbar navbar-inverse">
		<a class="navbar-brand" href="#">
			<span class="hidden-xs">SPORTS STORE</span>
			<div class="visible-xs">SPORTS</div>
			<div class="visible-xs">STORE</div>
			@Html.Action("Summary", "Cart")
		</a>
		@Html.Partial("_LoginPartial")

	</div>
	<div class="visible-xs">@Html.Action("Menu", "Nav", new { horizontalLayout = true })</div>

	<div class="row panel">
		<div class="col-sm-3 hidden-xs">
			@Html.Action("Menu", "Nav")
		</div>
		<div class="col-xs-12 col-sm-8">
			@RenderBody()
		</div>
	</div>
	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	<script src="~/Scripts/bootstrap.min.js"></script>
	@RenderSection("Scripts", required: false)
</body>
</html>