SportsStore.WebUI/Controllers/AdminController.cs
using SportsStore.Core.Interfaces.Managers;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SportsStore.WebUI.Models.Product;

namespace SportsStore.WebUI.Controllers
{
	[Authorize]
	[Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
		private readonly IProductManager _productManager;

		public AdminController(IProductManager productManager)
		{
			_productManager = productManager;
		}
		// GET: Admin
		public ActionResult Index()
        {
			var products = _productManager.GetAllProducts();
			return View(products);
		}
		[HttpGet]
		public ActionResult AddNewProduct()
		{
			return View("ProductDetails", new ProductModel());
		}

		[HttpPost]
		public ActionResult AddNewProduct(ProductModel product, HttpPostedFileBase image = null)
		{
			

			if (ModelState.IsValid)
			{
				if (image != null)
				{
					product.ImageMimeType = image.ContentType;
					product.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(product.ImageData, 0, image.ContentLength);
				}
				_productManager.AddProduct(product.Name, product.Description, product.Category, product.Price, product.ImageMimeType, product.ImageData);
				TempData["message"] = $"{product.Name} has been saved";
				return RedirectToAction("Index");
			}
			return View("ProductDetails", product);
		}
		[HttpGet]
		public ActionResult EditProduct(int productId)
		{
			var model = GetProductModel(productId);
			return View("ProductDetails", model);
		}
		[HttpPost]
		public ActionResult EditProduct(ProductModel product, HttpPostedFileBase image = null)
		{

			if (ModelState.IsValid)
			{
				if (image != null)
				{
					product.ImageMimeType = image.ContentType;
					product.ImageData = new byte[image.ContentLength];
					image.InputStream.Read(product.ImageData, 0, image.ContentLength);
				}
				_productManager.EditProduct(product.ProductId, product.Name, product.Description, product.Category,
					product.Price, product.ImageMimeType, product.ImageData);
				TempData["message"] = $"{product.Name} has been saved";
				return RedirectToAction("Index");
			}

			return View("ProductDetails", product);
		}
		[HttpPost]
		public ActionResult DeleteProduct(ProductModel product)
		{
			var nameForDeleted = product.Name;
			_productManager.DeleteProduct(product.ProductId);
			TempData["message"] = $"{nameForDeleted} was deleted";
			return RedirectToAction("Index");
		}
		private ProductModel GetProductModel(int productId)
		{
			var product = _productManager.GetProductById(productId);
			var model = new ProductModel()
			{
				ProductId = product.ProductId,
				Description = product.Description,
				Name = product.Name,
				Price = product.Price,
				Category = product.Category,
				ImageData = product.ImageData,
				ImageMimeType = product.ImageMimeType
			};
			return model;
		}
	}
}

SportsStore.WebUI/Controllers/ProductController.cs
using SportsStore.Core.Interfaces.Managers;
using SportsStore.WebUI.Models.ProductListModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductManager _productManager;
		private int _pageSize = 4;
		public ProductController(IProductManager productManager)
        {
            _productManager = productManager;
        }
        // GET: Product
        public ViewResult List(string category, int page = 1)
        {
            var productListModel = new ProductListModel()
            {
				Products = _productManager.GetAllProducts()
				.Where(x=> category == null || x.Category == category)
				.OrderBy(x => x.ProductId).Skip((page - 1) * _pageSize).Take(_pageSize).ToArray(),

			PagingInfoModel = new PagingInfoModel()
			{
				TotalItems = category == null ? _productManager.GetAllProducts().Count() : _productManager.GetAllProducts().Where(x => x.Category == category).Count(),
				CurrentPage = page,
				ItemsPerPage = _pageSize
			},
				CurrentCategory = category
			};
			return View("List", productListModel);
        }
		public FileContentResult GetImage(int productId)
		{
			var product = _productManager.GetProductById(productId);
			if (product != null)
			{
				var foto = File(product.ImageData, product.ImageMimeType);
				return File(product.ImageData, product.ImageMimeType);
			}
			return null;
		}
	}
}

SportsStore.WebUI/Views/Admin/Index.cshtml
@model IEnumerable<SportsStore.Core.Models.Product>

@{
	ViewBag.Title = "Admin: All Products";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel panel-default">
	<div class="panel-heading">
		<h3>All Products</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-condensed table-bordered">
			<tr>
				<th class="text-right">ID</th>
				<th>Name</th>
				<th class="text-right">Price</th>
				<th class="text-center">Actions</th>
			</tr>
			@foreach (var item in Model)
			{
				<tr>
					<td class="text-right">@item.ProductId</td>
					<td>@Html.ActionLink(item.Name, "EditProduct", new { productId = item.ProductId })</td>
					<td class="text-right">@item.Price.ToString("c")</td>
					<td class="text-center">
						@using (Html.BeginForm("DeleteProduct", "Admin"))
						{
							@Html.Hidden("ProductId", item.ProductId)
							@Html.Hidden("Name", item.Name)
							<input type="submit" class="btn btn-default btn-xs" value="Delete" />
						}
					</td>
				</tr>
			}
		</table>
	</div>
	<div class="panel-footer text-center">
		@Html.ActionLink("Add a new product", "AddNewProduct", null, new { @class = "btn btn-default" })
	</div>
</div>

SportsStore.WebUI/Views/Admin/ProductDetails.cshtml
@using System.Data.Entity.Core.Objects
@model SportsStore.WebUI.Models.Product.ProductModel
@{
	ViewBag.Title = "Product Details";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
	var h3Text = Model.ProductId > 0 ? "Edit product" : "Create new product";
	var buttonText = Model.ProductId > 0 ? "Save" : "Create";
	var action = Model.ProductId > 0 ? "EditProduct" : "AddNewProduct";
}
<div class="panel">
	<div class="panel-heading">
		<h3>@h3Text</h3>
	</div>
	@using (Html.BeginForm(action, "Admin", FormMethod.Post, new { @class = "form-control-static", role = "form", enctype = "multipart/form-data" }))
	{
		<div class="panel-body">
			
			@Html.HiddenFor(x => x.ProductId)
			@foreach (var property in ViewData.ModelMetadata.Properties)
			{

				switch (property.PropertyName)
				{
					case "ProductId":
					case "ImageData":
					case "ImageMimeType":
						break;
					default:
						<div class="form-group">
							<label>@(property.DisplayName ?? property.PropertyName)</label>
							@if (property.PropertyName == "Description")
							{
								@Html.TextArea(property.PropertyName, null, new { @class = "form-control", rows = "5" })
							}
							else if (property.PropertyName == "Price" && action == "AddNewProduct")
							{
								@Html.TextBox(property.PropertyName, "", new { @class = "form-control" })
							}
							else
							{
								@Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
							}
							@Html.ValidationMessage(property.PropertyName)
						</div>
						break;
				}
			}
			<div class="form-group">
				<div style="position: relative;">
					<label>Image</label>
					<a class='btn' href='javascript:;'>
						Chose File...
						<input type="file" name="Image" size="40" style="position: absolute; z-index: 2; top: 0; left: 0; filter: alpha(opacity=0); opacity: 0; background-color: transparent; color: transparent;"
							   onchange='$("#upload-file-info").html($(this).val());' />
					</a>
					<span class='label label-info' id="upload-file-info"></span>
				</div>
				@if (@Model.ImageData == null)
				{
					<div class="form-control-static">No Image</div>
				}
				else
				{
					<img class="img-thumbnail" width="150" height="150" src=@Url.Action("GetImage", "Product", new {Model.ProductId}) />
				}
			</div>
		</div>
		<div class="panel-footer">
			<input type="submit" value="@buttonText" class="btn btn-primary" />
			@Html.ActionLink("Cancel and return to List", "Index", null, new { @class = "btn btn-default" })
		</div>
	}
</div>